version: '3.8'
services:
  transaction-api:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    working_dir: /app
    command: bash -c "pip install flask && python app.py"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
